### ISSUE TITLE
@DedicatedServerOnly and @ClientOnly remove entire class when applied to method member

### ISSUE THREAD

**Issue by donington** [QuiltMC/quilt-loader#132]
I noticed the new features added via commit 0678cdffae455be758b8a8617f8327974410e753, deprecating the `@Environment` annotation and replacing it with `@DedicatedServerOnly` and `@ClientOnly`.

In some test code I've been poking with, I had two methods that I updated to use the new code, but during startup my mixin that uses the class threw a `ClassNotFoundException` during startup.

Here's a simplified example:
```
class ServerObserver {
  @DedicatedServerOnly  // replacing @Environment(EnvType.SERVER)
  public void is_dedicated_server_environment() {}
  @ClientOnly  // replacing @Environment(EnvType.CLIENT)
  public void is_client_environment() {}
}
```

I can verify that it only failed when applied against a method by converting the example to fields.  This loaded fine:
```
class ServerObserver {
  @DedicatedServerOnly
  public boolean is_dedicated_server_environment = true;
  @ClientOnly
  public boolean is_client_environment = true;
}
```

I believe somehow the `QuiltEnvironmentAnnotationVisitor` is marking the whole class for removal when the annotation is applied against a method, but I have yet to determine why that would be happening.

**Comment by AlexIIL** [comment]
Can you upload the crash report?

**Comment by AlexIIL** [comment]
Erm, it's also possible that it's crashing while trying to remove methods - as opposed to intentionally stripping the class. In particular 0.17.5 actually had a bug where the lambda stripping functionality always crashed when it tried to apply - so if you're still using 0.17.5 can you try updating to 0.17.6-beta.1?

**Comment by donington** [comment]
I just tried updating to 0.17.6-beta.1 with the same results.  Just to verify, updating `gradle/libs.versions.toml` and rebuilding is all that's required, correct?  The logs still show 0.17.5 so maybe I skipped a step.

Anyway, here's the log: https://mclo.gs/X5Zbzey

**Comment by donington** [comment]
oops wrong button

**Comment by donington** [comment]
I just tried updating to 0.17.6-beta.1 with the same results.  Just to verify, updating `gradle/libs.versions.toml` and rebuilding is all that's required, correct?  The logs still show 0.17.5 so maybe I skipped a step.

Anyway, here's the log: https://mclo.gs/X5Zbzey

**Comment by AlexIIL** [comment]
Thanks! After looking at the mixin error it looks like it *might* have logged an error when it tried to load the class - so can you upload a log instead sorry?

**Comment by AlexIIL** [comment]
Erm, if you're based off the template repository then yes, updatuing `gradle/libs.versions.toml`, rebuilding, and potentially refreshing the project in your IDE (I only know if this is necessary in eclipse sorry) should be enough to change the quilt-loader version.

**Comment by donington** [comment]
Sorry if I wasn't clear, what I posted was the log from the client startup.  There wasn't a proper crash report generated.

The line `[11:25:24] [main/WARN] (Quilt Loader/Mixin) Error loading class: net/jandastroy/testmod/ServerObserver (java.lang.IllegalArgumentException: Unsupported api 0)` suggests to me that the entire class was just refused to load, and it spirals out of control from there.

Going a bit further with my testing (juggling kids sick at home as well lol) I removed the `@DedicatedServerOnly` method and it boots fine on the client but experiences the same crash on the server (spiraling out of control after Unsupported api 0).

Server log: https://mclo.gs/r0YULKx

**Comment by AlexIIL** [comment]
Oh, I'm very sorry: I should have noticed that! `(java.lang.IllegalArgumentException: Unsupported api 0)` was in the first log - and that's the exact bug that was fixed in `0.17.6-beta.1` - so if you can figure out how to update your loader version then that will fix the problem.

**Comment by donington** [comment]
Okay, latest test ran with `0.17.6-beta.1` properly.  Unfortunately, still the same error when a method is flagged for the opposite side.
Server Log - https://mclo.gs/Zi1pNgR

I made a git clone of quilt-loader to see if I can look deeper at why it only fails with methods but not fields overwritten, but I haven't quite figured out how to run a local edit yet.

**Comment by AlexIIL** [comment]
It turns out I didn't actually fix this bug in `0.17.6-beta.1`, but instead `0.17.6-beta.2`. I should have paid closer attention to what the actual latest version was, sorry :/

**Comment by donington** [comment]
Confirmed fixed in 0.17.6-beta.2.  Thanks for the help sorting that out, glad to see it working!
