### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by RhythmicSys** [QuiltMC/quilt-loader#152]
Currently trying to debug an issue with my modpack - and in the debug process have gotten [this crash](https://pastebin.com/hDKnf8Gt)
[Full Log](https://pastebin.com/SbVZKDGb)

**Other Info:**
Had an issue with [this modpack](https://modrinth.com/modpack/accessibility/version/1.3.0) where the options screen was [causing a crash](https://pastebin.com/Rt17Td5i) that didn't seem to have any mods attached 
[Full Log](https://pastebin.com/0kaC7t8x)

I copied over the mods and mod configs from the instance that was having this issue, onto a fresh instance (made a new mod directory and config directory manually, and copied over the mod configs and mods)

I did not copy over the sub-folders, since I wanted them to generate new ones

Config directory in modpack that was crashing when options was clicked:
![image](https://user-images.githubusercontent.com/45906780/202631298-2685ba13-a62b-439e-970b-17fbc7b47ce6.png)

Config directory in modpack that crashes on startup:
![image](https://user-images.githubusercontent.com/45906780/202631423-eb04b352-735d-400e-8568-0bdb70ca61fc.png)

**Comment by AlexIIL** [comment]
Thanks for the report! I've pushed a fix for the first issue in `0.18.1-beta.15`.

The second error is probably because you've installed the `1.16.5` version of ukulib, rather than the 1.19.2 version?

**Comment by RhythmicSys** [comment]
Version `0.18.1-beta.15` manages to load more than before, but still crashes before the game boots up
[New Crash Report](https://pastebin.com/Zp4RRakp), [Full Log](https://pastebin.com/xpDeX8MJ)

And for the second one, thanks, didn't realize there were different versions since that's the only one that showed up on packwiz lol 🤦🏻

**Comment by AlexIIL** [comment]
It turns out I broke how dependencies are handled a few days ago - so that crash is probably caused by that. Can you try updating to beta.16?

**Comment by RhythmicSys** [comment]
That version works :D
